repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        name: poetry-lock-check
        args: ["--check"]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.2.1"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
